events {}

http {
  server {
    listen 80;

    # ✅ Serve static directly from nginx filesystem
    location /static/ {
      alias /usr/share/nginx/html/static/;
      access_log off;
      expires 1h;
      add_header Cache-Control "public";
    }

    # Main app
    location / {
      proxy_pass http://app:5000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
